#!/usr/bin/env python
"""Export Unreal Editor bake data/script for Phase 1 track elements.

Run this outside Unreal. It writes:

- ``carla_autodrive/unreal_bake/skku_track_layout.json``
- ``carla_autodrive/unreal_bake/bake_skku_track_layout.py``

Open the CARLA Unreal project in the editor and run the generated Python script
to place persistent StaticMesh markers and TriggerBox volumes in the level.
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from carla_autodrive.maps import TrackPose, TrackSpec
from carla_autodrive.missions import mission_elements, parking_zone_pose

OUT_DIR = Path(__file__).resolve().parent.parent / "unreal_bake"


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="Phase 1: generate Unreal Editor bake outputs")
    ap.add_argument("--out-dir", type=Path, default=OUT_DIR)
    return ap.parse_args()


def pose_dict(pose: TrackPose, z: float = 0.0) -> dict:
    return {
        "x": pose.x,
        "y": pose.y,
        "z": z,
        "yaw_deg": math.degrees(pose.heading),
        "s": pose.s,
        "lane": pose.lane,
    }


def zone_dict(name: str, kind: str, pose: TrackPose, length: float, width: float) -> dict:
    return {
        "name": name,
        "kind": kind,
        "pose": pose_dict(pose, 0.05),
        "length": length,
        "width": width,
        "height": 1.5,
    }


def build_zones(spec: TrackSpec) -> list[dict]:
    dims = spec.cfg["dimensions"]
    elements = mission_elements(spec)
    zones = [
        zone_dict("start_line", "lap", spec.road_center_pose(elements["start_line"]["s"]),
                  spec.mm(dims["start_line_mm"]), spec.road_width),
        zone_dict("laptimer_T4", "lap", spec.road_center_pose(elements["laptimer_T4"]["s"]),
                  spec.mm(dims["start_line_mm"]), spec.road_width),
        zone_dict("crosswalk", "traffic", spec.road_center_pose(elements["crosswalk"]["s"]),
                  spec.mm(dims["crosswalk_mm"][1]), spec.mm(dims["crosswalk_mm"][0])),
    ]
    for key in ("parking_zone1", "parking_zone2"):
        item = elements[key]
        zone_idx = int(key.removeprefix("parking_zone"))
        slot = item.get("slot", {}) if isinstance(item, dict) else {}
        parking_length = spec.mm(slot.get("length_mm", dims["parking_mm"][1]))
        parking_width = spec.mm(slot.get("width_mm", dims["parking_mm"][0]))
        zones.append(zone_dict(key, "parking", parking_zone_pose(spec, zone_idx),
                               parking_length, parking_width))
    return zones


def build_obstacles(spec: TrackSpec) -> list[dict]:
    elements = mission_elements(spec)
    items = [("obstacle_1", elements["obstacle_1"])]
    items.append(("obstacle_2_p0", elements["obstacle_2_presets"][0]))
    items.append(("obstacle_3_p0", elements["obstacle_3_presets"][0]))
    out = []
    for name, item in items:
        out.append({
            "name": name,
            "pose": pose_dict(spec.lane_center_pose(item["s"], item["lane"]), 0.35),
            "length": 4.5,
            "width": 1.8,
            "height": 1.6,
        })
    return out


def build_layout(spec: TrackSpec) -> dict:
    crosswalk = spec.road_center_pose(mission_elements(spec)["crosswalk"]["s"])
    traffic_light = {
        "name": "traffic_light_crosswalk",
        "pose": pose_dict(crosswalk, 8.0),
        "static_mesh_hint": "Signal_3Light_Post01",
    }

    return {
        "meta": {
            "name": spec.name,
            "scale": spec.scale,
            "units": "CARLA meters for x/y/z/length/width; Unreal centimeters after conversion",
        },
        "dimensions": {
            "road_width": spec.road_width,
            "lane_width": spec.lane_width,
            "total_length": spec.total_length(),
        },
        "zones": build_zones(spec),
        "obstacles": build_obstacles(spec),
        "traffic_lights": [traffic_light],
    }


def bake_script() -> str:
    return r'''"""Unreal Editor bake script generated by export_unreal_bake.py.

Usage in Unreal Editor:
  1. Open CARLA_0.9.16/CarlaUE4/CarlaUE4.uproject in Unreal Editor.
  2. Open the target level.
  3. Run this file from the Output Log with:
     py "/absolute/path/to/carla_autodrive/unreal_bake/bake_skku_track_layout.py"

The script places simple persistent StaticMeshActor boxes plus TriggerBox
volumes. Replace the cube meshes with final CAD/static meshes when available.
"""
from __future__ import annotations

import json
from pathlib import Path

import unreal

LAYOUT_PATH = Path(__file__).with_name("skku_track_layout.json")
CM_PER_M = 100.0


def load_layout():
    with LAYOUT_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)


def vec_m(x, y, z):
    return unreal.Vector(x * CM_PER_M, y * CM_PER_M, z * CM_PER_M)


def rot_yaw(yaw_deg):
    return unreal.Rotator(0.0, yaw_deg, 0.0)


def spawn_cube(name, pose, length_m, width_m, height_m):
    mesh = unreal.EditorAssetLibrary.load_asset("/Engine/BasicShapes/Cube.Cube")
    actor = unreal.EditorLevelLibrary.spawn_actor_from_class(
        unreal.StaticMeshActor,
        vec_m(pose["x"], pose["y"], pose.get("z", 0.0)),
        rot_yaw(pose["yaw_deg"]),
    )
    actor.set_actor_label(name)
    comp = actor.static_mesh_component
    comp.set_static_mesh(mesh)
    # Engine cube is 100cm per side; scale 1.0 equals 1m.
    actor.set_actor_scale3d(unreal.Vector(length_m, width_m, height_m))
    return actor


def spawn_trigger(name, pose, length_m, width_m, height_m):
    actor = unreal.EditorLevelLibrary.spawn_actor_from_class(
        unreal.TriggerBox,
        vec_m(pose["x"], pose["y"], pose.get("z", 0.0)),
        rot_yaw(pose["yaw_deg"]),
    )
    actor.set_actor_label(f"TRIGGER_{name}")
    actor.set_actor_scale3d(unreal.Vector(length_m / 2.0, width_m / 2.0, height_m / 2.0))
    return actor


def main():
    layout = load_layout()
    for zone in layout["zones"]:
        pose = zone["pose"]
        spawn_cube(f"ZONE_{zone['name']}", pose, zone["length"], zone["width"], 0.08)
        spawn_trigger(zone["name"], pose, zone["length"], zone["width"], zone["height"])

    for obstacle in layout["obstacles"]:
        spawn_cube(f"OBSTACLE_{obstacle['name']}", obstacle["pose"],
                   obstacle["length"], obstacle["width"], obstacle["height"])

    for signal in layout["traffic_lights"]:
        spawn_cube(signal["name"], signal["pose"], 0.6, 0.6, 2.2)

    unreal.EditorLevelLibrary.save_current_level()
    unreal.log(f"SKKU_AD_Track bake complete: {len(layout['zones'])} zones")


main()
'''


def main() -> int:
    args = parse_args()
    spec = TrackSpec()
    layout = build_layout(spec)
    args.out_dir.mkdir(parents=True, exist_ok=True)

    layout_path = args.out_dir / "skku_track_layout.json"
    script_path = args.out_dir / "bake_skku_track_layout.py"
    layout_path.write_text(json.dumps(layout, ensure_ascii=False, indent=2), encoding="utf-8")
    script_path.write_text(bake_script(), encoding="utf-8")
    print(f"wrote {layout_path}")
    print(f"wrote {script_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
