#!/usr/bin/env python
"""Fit ``config/track.yaml`` centerline to ``circuit_blueprint.png``.

This is a deterministic image-fitting pipeline, not a trained ML model:

1. Extract a blueprint mask.
2. Project the current track centerline into image space.
3. Iteratively move the closed polyline toward the mask with smoothing.
4. Resample it into YAML control points.
5. Optionally apply the result to ``config/track.yaml`` with a backup.

The current YAML acts as the prior, so the generated track keeps a stable order
and avoids arbitrary jumps that pure image skeleton extraction can produce.
"""
from __future__ import annotations

import argparse
import json
import math
import shutil
import sys
from pathlib import Path

import numpy as np
import yaml
from PIL import Image, ImageDraw
from scipy.spatial import cKDTree

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from carla_autodrive.maps import TrackSpec
from carla_autodrive.scripts.measure_track_accuracy import (
    bbox_from_mask,
    distances,
    filter_component,
    mask_pixels,
    project_mm_to_px,
    summarize,
)

ROOT = Path(__file__).resolve().parent.parent.parent
CONFIG_PATH = ROOT / "carla_autodrive" / "config" / "track.yaml"
DEFAULT_IMAGE = ROOT / "circuit_blueprint.png"
DEFAULT_OUT = ROOT / "carla_autodrive" / "reports"


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="automatically adjust the track.yaml centerline from a blueprint image")
    ap.add_argument("--image", type=Path, default=DEFAULT_IMAGE)
    ap.add_argument("--track-yaml", type=Path, default=CONFIG_PATH)
    ap.add_argument("--mask", choices=("green", "red", "dark", "nonwhite"), default="nonwhite")
    ap.add_argument("--component", choices=("all", "largest"), default="largest")
    ap.add_argument("--probability-mask", type=Path, default=None,
                    help="grayscale probability-mask PNG generated by the trained model")
    ap.add_argument("--prob-threshold", type=float, default=0.45,
                    help="positive mask threshold used with --probability-mask (0 to 1)")
    ap.add_argument("--samples", type=int, default=360, help="number of closed-curve samples to optimize")
    ap.add_argument("--control-points", type=int, default=36, help="number of YAML control points to save")
    ap.add_argument("--iterations", type=int, default=120)
    ap.add_argument("--learning-rate", type=float, default=0.35)
    ap.add_argument("--coverage-weight", type=float, default=0.20,
                    help="weight that keeps blueprint pixels distributed across the whole track")
    ap.add_argument("--smooth", type=float, default=0.18, help="circular smoothing strength from 0 to 1")
    ap.add_argument("--max-step-px", type=float, default=18.0)
    ap.add_argument("--tolerance-mm", type=float, default=None)
    ap.add_argument("--apply", action="store_true", help="apply to config/track.yaml and create a .bak backup")
    ap.add_argument("--out-yaml", type=Path, default=DEFAULT_OUT / "track_fitted.yaml")
    ap.add_argument("--json-name", default="track_fit_report.json")
    ap.add_argument("--overlay-name", default="track_fit_overlay.png")
    return ap.parse_args()


def load_yaml(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def write_yaml(path: Path, cfg: dict) -> None:
    text = yaml.safe_dump(cfg, allow_unicode=True, sort_keys=False, width=1000)
    header = (
        "# SKKU_AD_Track - blueprint-fitted track.yaml\n"
        "# Auto-generated by carla_autodrive.scripts.fit_track_from_blueprint.\n"
        "# Units are real-world millimeters; CARLA coordinates apply meta.scale.\n\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(header + text, encoding="utf-8")


def centerline_samples_mm(spec: TrackSpec, count: int) -> np.ndarray:
    total_mm = spec.total_length() / spec.scale * 1000.0
    pts = []
    for i in range(count):
        pose = spec.reference_pose_at(spec.mm(total_mm * i / count))
        pts.append((pose.x / spec.scale * 1000.0, pose.y / spec.scale * 1000.0))
    return np.asarray(pts, dtype=np.float64)


def pixel_to_mm(points_px: np.ndarray, field_mm: tuple[float, float],
                bbox: tuple[int, int, int, int]) -> np.ndarray:
    x0, y0, x1, y1 = bbox
    sx = (x1 - x0) / field_mm[0]
    sy = (y1 - y0) / field_mm[1]
    out = np.empty_like(points_px)
    out[:, 0] = (points_px[:, 0] - x0) / sx
    out[:, 1] = (points_px[:, 1] - y0) / sy
    return out


def resample_closed(points: np.ndarray, count: int) -> np.ndarray:
    nxt = np.roll(points, -1, axis=0)
    seg = np.linalg.norm(nxt - points, axis=1)
    total = float(seg.sum())
    if total <= 1e-9:
        raise ValueError("cannot resample a zero-length polyline.")
    cumulative = np.concatenate([[0.0], np.cumsum(seg)])
    targets = np.linspace(0.0, total, count, endpoint=False)
    out = []
    for t in targets:
        idx = int(np.searchsorted(cumulative, t, side="right") - 1)
        idx = min(idx, len(points) - 1)
        local = (t - cumulative[idx]) / max(seg[idx], 1e-9)
        out.append(points[idx] * (1.0 - local) + points[(idx + 1) % len(points)] * local)
    return np.asarray(out)


def rotate_to_nearest_start(points: np.ndarray, start_mm: np.ndarray) -> np.ndarray:
    idx = int(np.argmin(np.linalg.norm(points - start_mm[None, :], axis=1)))
    return np.concatenate([points[idx:], points[:idx]], axis=0)


def chamfer_report(track_px: np.ndarray, mask: np.ndarray, scales: tuple[float, float], tolerance_mm: float) -> dict:
    track_to_mask, mask_to_track, _ = distances(track_px, mask)
    px_to_mm = 1.0 / ((scales[0] + scales[1]) / 2.0)
    tolerance_px = tolerance_mm / px_to_mm
    a = summarize(track_to_mask, px_to_mm, tolerance_px)
    b = summarize(mask_to_track, px_to_mm, tolerance_px)
    return {
        "track_to_blueprint": a,
        "blueprint_to_track": b,
        "estimated_shape_accuracy_percent": (a["within_tolerance_percent"] + b["within_tolerance_percent"]) / 2.0,
        "bidirectional_mean_error_mm": (a["mean_mm"] + b["mean_mm"]) / 2.0,
    }


def optimize(points_px: np.ndarray, mask: np.ndarray, args: argparse.Namespace) -> np.ndarray:
    ys, xs = np.where(mask)
    target = np.column_stack([xs, ys]).astype(np.float64)
    if len(target) > 50000:
        rng = np.random.default_rng(11)
        target = target[rng.choice(len(target), size=50000, replace=False)]

    target_tree = cKDTree(target)
    pts = points_px.copy()
    for _ in range(args.iterations):
        nearest_dist, nearest_idx = target_tree.query(pts, k=1)
        nearest = target[nearest_idx]
        snap_force = nearest - pts

        track_tree = cKDTree(pts)
        _, owner = track_tree.query(target, k=1)
        sums = np.zeros_like(pts)
        counts = np.zeros(len(pts), dtype=np.float64)
        np.add.at(sums, owner, target)
        np.add.at(counts, owner, 1.0)
        coverage_force = np.zeros_like(pts)
        has = counts > 0
        coverage_force[has] = sums[has] / counts[has, None] - pts[has]

        step = args.learning_rate * (snap_force + args.coverage_weight * coverage_force)
        norm = np.linalg.norm(step, axis=1)
        too_big = norm > args.max_step_px
        step[too_big] *= args.max_step_px / norm[too_big, None]
        pts = pts + step

        if args.smooth > 0.0:
            neighbor_avg = 0.5 * (np.roll(pts, 1, axis=0) + np.roll(pts, -1, axis=0))
            pts = (1.0 - args.smooth) * pts + args.smooth * neighbor_avg
    return pts


def draw_overlay(image: Image.Image, mask: np.ndarray, before: np.ndarray, after: np.ndarray, out_path: Path) -> None:
    overlay = image.convert("RGBA")
    layer = Image.new("RGBA", image.size, (0, 0, 0, 0))
    arr = np.asarray(layer).copy()
    arr[mask] = (0, 180, 0, 95)
    overlay = Image.alpha_composite(overlay, Image.fromarray(arr))
    draw = ImageDraw.Draw(overlay)
    before_pts = [(float(x), float(y)) for x, y in before]
    after_pts = [(float(x), float(y)) for x, y in after]
    draw.line(before_pts + [before_pts[0]], fill=(255, 140, 0, 220), width=5)
    draw.line(after_pts + [after_pts[0]], fill=(255, 0, 0, 255), width=6)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    overlay.convert("RGB").save(out_path)


def main() -> int:
    args = parse_args()
    cfg = load_yaml(args.track_yaml)
    spec = TrackSpec(cfg)

    image = Image.open(args.image).convert("RGB")
    rgb = np.asarray(image)
    if args.probability_mask is not None:
        prob = np.asarray(Image.open(args.probability_mask).convert("L"), dtype=np.float32) / 255.0
        raw_mask = prob >= args.prob_threshold
    else:
        raw_mask = mask_pixels(rgb, args.mask)
    mask = filter_component(raw_mask, args.component)
    bbox = bbox_from_mask(mask)
    field_mm = tuple(float(v) for v in cfg["dimensions"]["field_mm"])
    tolerance_mm = args.tolerance_mm
    if tolerance_mm is None:
        tolerance_mm = float(cfg["dimensions"]["road_width_mm"]) / 2.0

    before_mm = centerline_samples_mm(spec, args.samples)
    before_px, scales = project_mm_to_px(before_mm, field_mm, bbox)
    after_px = optimize(before_px, mask, args)
    after_mm = pixel_to_mm(after_px, field_mm, bbox)

    start = np.asarray([cfg["centerline"]["control_points"][0]["x"], cfg["centerline"]["control_points"][0]["y"]], dtype=np.float64)
    controls = rotate_to_nearest_start(resample_closed(after_mm, args.control_points), start)
    controls = np.clip(controls, [0.0, 0.0], [field_mm[0], field_mm[1]])

    out_cfg = dict(cfg)
    out_cfg["centerline"] = dict(cfg["centerline"])
    out_cfg["centerline"]["mode"] = "spline"
    out_cfg["centerline"]["samples_per_segment"] = int(cfg["centerline"].get("samples_per_segment", 16))
    out_cfg["centerline"]["tension"] = float(cfg["centerline"].get("tension", 0.5))
    out_cfg["centerline"]["control_points"] = [
        {"x": int(round(x)), "y": int(round(y))} for x, y in controls
    ]

    before_report = chamfer_report(before_px, mask, scales, tolerance_mm)
    control_px, _ = project_mm_to_px(controls, field_mm, bbox)
    after_report = chamfer_report(after_px, mask, scales, tolerance_mm)

    args.out_yaml.parent.mkdir(parents=True, exist_ok=True)
    write_yaml(args.out_yaml, out_cfg)

    json_path = DEFAULT_OUT / args.json_name
    overlay_path = DEFAULT_OUT / args.overlay_name
    report = {
        "image": str(args.image),
        "track_yaml": str(args.track_yaml),
        "mask": args.mask,
        "component": args.component,
        "probability_mask": str(args.probability_mask) if args.probability_mask is not None else None,
        "prob_threshold": args.prob_threshold,
        "raw_mask_pixels": int(raw_mask.sum()),
        "mask_pixels": int(mask.sum()),
        "mask_bbox_px": list(bbox),
        "field_mm": list(field_mm),
        "tolerance_mm": float(tolerance_mm),
        "samples": args.samples,
        "control_points": args.control_points,
        "before": before_report,
        "after_optimized_polyline": after_report,
        "out_yaml": str(args.out_yaml),
        "applied": bool(args.apply),
        "notes": [
            "Orange overlay is the previous track; red overlay is the fitted track.",
            "The YAML stores resampled control points, so final build accuracy can differ slightly from optimized polyline accuracy.",
        ],
    }
    json_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    draw_overlay(image, mask, before_px, control_px, overlay_path)

    if args.apply:
        backup = args.track_yaml.with_suffix(args.track_yaml.suffix + ".bak")
        shutil.copy2(args.track_yaml, backup)
        write_yaml(args.track_yaml, out_cfg)
        report["backup"] = str(backup)
        json_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"mask={args.mask} component={args.component} raw_pixels={int(raw_mask.sum())} pixels={int(mask.sum())}")
    print("before accuracy={:.1f}% mean_error={:.1f}mm".format(
        before_report["estimated_shape_accuracy_percent"], before_report["bidirectional_mean_error_mm"]))
    print("after  accuracy={:.1f}% mean_error={:.1f}mm".format(
        after_report["estimated_shape_accuracy_percent"], after_report["bidirectional_mean_error_mm"]))
    print(f"wrote {args.out_yaml}")
    print(f"wrote {json_path}")
    print(f"wrote {overlay_path}")
    if args.apply:
        print(f"applied {args.track_yaml}")
        print(f"backup {backup}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
