"""Unreal Editor bake script generated by export_unreal_bake.py.

Usage in Unreal Editor:
  1. Open CARLA_0.9.16/CarlaUE4/CarlaUE4.uproject in Unreal Editor.
  2. Open the target level.
  3. Run this file from the Output Log with:
     py "/absolute/path/to/carla_autodrive/unreal_bake/bake_skku_track_layout.py"

The script places simple persistent StaticMeshActor boxes plus TriggerBox
volumes. Replace the cube meshes with final CAD/static meshes when available.
"""
from __future__ import annotations

import json
from pathlib import Path

import unreal

LAYOUT_PATH = Path(__file__).with_name("skku_track_layout.json")
CM_PER_M = 100.0


def load_layout():
    with LAYOUT_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)


def vec_m(x, y, z):
    return unreal.Vector(x * CM_PER_M, y * CM_PER_M, z * CM_PER_M)


def rot_yaw(yaw_deg):
    return unreal.Rotator(0.0, yaw_deg, 0.0)


def spawn_cube(name, pose, length_m, width_m, height_m):
    mesh = unreal.EditorAssetLibrary.load_asset("/Engine/BasicShapes/Cube.Cube")
    actor = unreal.EditorLevelLibrary.spawn_actor_from_class(
        unreal.StaticMeshActor,
        vec_m(pose["x"], pose["y"], pose.get("z", 0.0)),
        rot_yaw(pose["yaw_deg"]),
    )
    actor.set_actor_label(name)
    comp = actor.static_mesh_component
    comp.set_static_mesh(mesh)
    # Engine cube is 100cm per side; scale 1.0 equals 1m.
    actor.set_actor_scale3d(unreal.Vector(length_m, width_m, height_m))
    return actor


def spawn_trigger(name, pose, length_m, width_m, height_m):
    actor = unreal.EditorLevelLibrary.spawn_actor_from_class(
        unreal.TriggerBox,
        vec_m(pose["x"], pose["y"], pose.get("z", 0.0)),
        rot_yaw(pose["yaw_deg"]),
    )
    actor.set_actor_label(f"TRIGGER_{name}")
    actor.set_actor_scale3d(unreal.Vector(length_m / 2.0, width_m / 2.0, height_m / 2.0))
    return actor


def main():
    layout = load_layout()
    for zone in layout["zones"]:
        pose = zone["pose"]
        spawn_cube(f"ZONE_{zone['name']}", pose, zone["length"], zone["width"], 0.08)
        spawn_trigger(zone["name"], pose, zone["length"], zone["width"], zone["height"])

    for obstacle in layout["obstacles"]:
        spawn_cube(f"OBSTACLE_{obstacle['name']}", obstacle["pose"],
                   obstacle["length"], obstacle["width"], obstacle["height"])

    for signal in layout["traffic_lights"]:
        spawn_cube(signal["name"], signal["pose"], 0.6, 0.6, 2.2)

    unreal.EditorLevelLibrary.save_current_level()
    unreal.log(f"SKKU_AD_Track bake complete: {len(layout['zones'])} zones")


main()
